### ISSUE TITLE
关于使用使用到的xfbinst

### ISSUE THREAD

**Issue by horatii** [linuxdeepin/deepin-boot-maker#10]
我在所类似的工作，看到这个工程中有使用到xfbinst，xfbinst的能不能提供一下源码？和原有的fbinst的源码有什么改进的地方？

**Comment by Iceyer** [comment]
和fbint的区别是增加了对macos的支持。源码可以从这里获取：
https://coding.net/u/iceyer/p/xfbinst/git

**Comment by horatii** [comment]
非常感谢
