### ISSUE TITLE
可以用dd制作启动盘吗？

### ISSUE THREAD

**Issue by stainboy** [linuxdeepin/deepin-boot-maker#11]
大部分Linux发行版（如fedora, archlinux）可以直接 `dd if=/path/to/live-image.iso of=/dev/sdX bs=8M` 制作启动盘。不知deepin live image可以这样做吗？

**Comment by urain39** [comment]
好像可以的

**Comment by 21wmd** [comment]
Deepin 也支持 dd 的方式制作启动盘

≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣≣
Best Regards,
wangmd21

**Comment by Iceyer** [comment]
支持DD，不过15.3 ~ 15.4 目前屏蔽了live模式，只有安装模式可以使用。
