### ISSUE TITLE
Linux下无法安装深度启动盘制作工具

### ISSUE THREAD

**Issue by mokongh** [linuxdeepin/deepin-boot-maker#16]
正在选中未选择的软件包 deepin-boot-maker。
(正在读取数据库 ... 系统当前共安装有 231455 个文件和目录。)
正准备解包 deep.deb  ...
正在解包 deepin-boot-maker (2.0.0-1) ...
dpkg: 依赖关系问题使得 deepin-boot-maker 的配置工作不能继续：
 deepin-boot-maker 依赖于 libdtkbase (>= 0.2.9)；然而：
  未安装软件包 libdtkbase。
 deepin-boot-maker 依赖于 libdtkutil (>= 0.2.9)；然而：
  未安装软件包 libdtkutil。
 deepin-boot-maker 依赖于 libdtkwidget (>= 0.2.9)；然而：
  未安装软件包 libdtkwidget。
 deepin-boot-maker 依赖于 libqt5x11extras5 (>= 5.6.0)；然而：
  未安装软件包 libqt5x11extras5。
 deepin-boot-maker 依赖于 libxcb-util0 (>= 0.3.8)；然而：
  未安装软件包 libxcb-util0。

dpkg: 处理软件包 deepin-boot-maker (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 gnome-menus (3.13.3-6ubuntu5) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1ubuntu2) 的触发器 ...
正在处理用于 mime-support (3.60ubuntu1) 的触发器 ...
正在处理用于 dbus (1.10.10-1ubuntu2) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.15-1) 的触发器 ...
在处理时有错误发生：
 deepin-boot-maker

这些软件包应该到哪里去下载？

**Comment by Iceyer** [comment]
@mokongh 如果你不是debian的系统，我估计你这个装上有点难。
http://packages.deepin.com/deepin/pool/main/d/deepin-tool-kit/
http://packages.deepin.com/deepin/pool/main/d/dtksettings/

依赖libdtkbase/libdtkutil/libdtkwidget/libdtksettings/libdtksettingsview
