### ISSUE TITLE
make libxsys an individual repo

### ISSUE THREAD

**Issue by yangfl** [linuxdeepin/deepin-boot-maker#19]
It seems that libxsys is an individual library. And there was a repo for it https://github.com/Iceyer/libxsys. Separating it may better organize the code.
Also current lib is statically linked, please avoid it.

**Comment by yangfl** [comment]
Here are some possible statically-linked libraries from lintian.
```
E: deepin-boot-maker: embedded-library usr/bin/deepin-boot-maker: libpng
E: deepin-boot-maker: embedded-library usr/bin/deepin-boot-maker: zlib
E: deepin-boot-maker: embedded-library usr/lib/deepin-daemon/deepin-boot-maker-service: libpng
E: deepin-boot-maker: embedded-library usr/lib/deepin-daemon/deepin-boot-maker-service: zlib
```

**Comment by Iceyer** [comment]
This is an old issue, deepin-boot-maker was statically linked in the early few releases. I will fix it next week.
And libxsys is not maintained for a long long time. I want this library work for deepin-windows-installer and deepin-boot-maker, but finally, I abandon this work. So just keep libxsys in deepin-boot-maker, I will not maintain  https://github.com/Iceyer/libxsys unless I decide to prot deepin-windows-installer to linux/mac.
