### ISSUE TITLE
No available disk found

### ISSUE THREAD

**Issue by YuhanXu** [linuxdeepin/deepin-boot-maker#20]
deepin-boot-maker is installed on mac 10.13.1,
Kingsoft USB exFAT format is plugged in the mac,
Open deepin-boot-maker,
win10_1709 .ISO official ISO file can be loaded,
Hit NEXT, "No available disk found".

**Comment by YuhanXu** [comment]
Problem Solved！
I changed the USB format to MS-DOS, then I USB device can be found.

**Comment by mohit2494** [comment]
How to change the USB format to MS-DOS?

**Comment by hjJunior** [comment]
I'm having the same issue even after format to MS-DOS (FAT) and also I tried (FAT32)

<img width="451" alt="image" src="https://user-images.githubusercontent.com/10780132/157935849-14f33e55-57f5-49dd-b84b-5245af363537.png">
