### ISSUE TITLE
官方下载地址 404

### ISSUE THREAD

**Issue by necan** [linuxdeepin/deepin-boot-maker#25]
> 下载地址
> Windows下载地址： http://cdimage.deepin.com/applications/deepin-boot-maker/windows/
> MacOS下载地址： http://cdimage.deepin.com/applications/deepin-boot-maker/macos/

官方下载地址 404，无法下载，请更新下载地址。

**Comment by BLumia** [comment]
@wangjia12

**Comment by nangy2514** [comment]
404 Not Found

**Comment by BLumia** [comment]
https://www.deepin.org/original/deepin-boot-maker/ 页面的链接还没有更新 @lq95v5

**Comment by lq95v5** [comment]
Windows下载地址： http://cdimage.deepin.com/applications/deepin-boot-maker/windows/
MacOS下载地址： http://cdimage.deepin.com/applications/deepin-boot-maker/macos/

cdimage.deepin.com目前服务器坏了。。 
iso文件中带有deepinbootmaker
http://202.141.160.113:8088/ 里面也没有

@hualet
