### ISSUE TITLE
Can't build on OSX 10.11

### ISSUE THREAD

**Issue by seadog007** [linuxdeepin/deepin-boot-maker#7]
And the example path is also wrong.
<img width="1280" alt="2015-12-18 1 28 25" src="https://cloud.githubusercontent.com/assets/5138409/11890058/409a4784-a58b-11e5-82e0-31f890d6478e.png">

**Comment by Iceyer** [comment]
there is no problem now， we run ci on each commit， you can get build status from here:

https://ci.deepin.io/view/apps%20on%20osx/job/deepin-boot-maker-osx-ci/
